### ISSUE TITLE
Introduce infix `or` function

### ISSUE THREAD

**Issue by dmitry-novikov** [gojuno/koptional#10]
It will be really handy to have infix `or` function in `Optional` for fallback to default value in case of `None` like:
```kotlin
val some = Some(1)
val someOrDefault = some or 2
```

**Comment by artem-zinnatullin** [comment]
What I don't like about it is that it adds a second way to get default value to existing one `o.toNullable() ?: "fallback"`, that was one of the things we were trying to remove — ambiguity…

Also in a real-life case, it might be not obvious because `or` is also defined for `Int`, `Long` and `Boolean` by Kotlin stdlib which could be used as `Optional<>` values quite often and might lead to wrong results of operation.

However, it's a shorter notation and fits `Optional` use case quite well…

Any input @ming13, @igor-korotenko, @nostra13, @igorab?

**Comment by nostra13** [comment]
I agree with @artem-zinnatullin  about possible confusing `or` considering existing binary operator.
`some or 2` and `some.value or 2` are similar but will produce different results.

**Comment by ming13** [comment]
Against it for two reasons.

* The goal of the library is to refer to Kotlin syntax. `or` is the same as `o.toNullable() ?: value`.
* It is kind of impractical for nesting — `(o or ).method()`.

**Comment by artem-zinnatullin** [comment]
Closing this for now then
